### PR TITLE
Fix #496: compatibility with cgroup v2

### LINKED ISSUE #496: Worker setup fails on Linux distibutions that use cgroup v2
**Describe the bug**
On Linux distributions that use cgroup v2, when a workflow is started, the apps are never executed and the workflow never completes.

According to [this source](https://rootlesscontaine.rs/getting-started/common/cgroup2/), Linux distributions that use cgroup v2 include :
- Fedora >=31 (October 2019)
- Arch Linux (since April 2021)
- openSUSE Tumbleweed (since c. 2021)
- Debian >= 11 (August 2021)

**To Reproduce**
1. Install Shuffle on a Linux distribution that uses cgroup v2
2. Create any workflow with at least one app
3. Start the workflow
...

**Expected behavior**
The apps are executed and the workflow completes.

**Debug logs**
I don't have access to the full logs, however, we have found that the worker logs contain these warnings:
```
[WARNING] No container ID found. Not running containerized? This should only show during testing
[WARNING] Empty self container id, continue without NetworkMode
```
---
The warnings come from this code:
https://github.com/frikky/Shuffle/blob/d77ae8260fd32691d8942dece1957915ba1ff3d5/functions/onprem/worker/worker.go#L87-L92
https://github.com/frikky/Shuffle/blob/d77ae8260fd32691d8942dece1957915ba1ff3d5/functions/onprem/worker/worker.go#L221-L226

The issue seems to be with the technique used to get the container id:
https://github.com/frikky/Shuffle/blob/d77ae8260fd32691d8942dece1957915ba1ff3d5/functions/onprem/worker/worker.go#L66-L73

With cgroup v2, the content of `/proc/self/cgroup` [doesn't include the container id anymore](https://docs.docker.com/config/containers/runmetrics/#enumerate-cgroups).

That leads the the NetworkMode of the apps being set incorrectly. The same issue happens for the worker, but with less warnings in the logs:
https://github.com/frikky/Shuffle/blob/d77ae8260fd32691d8942dece1957915ba1ff3d5/functions/onprem/orborus/orborus.go#L143-L148

We haven't found a way to get the container id from inside the container with cgroup v2 (aside from sending it to the container from the outside after the container is created).

However, I believe that the container id is not required to setup the networking mode correctly.
The [Docker API docs](https://docs.docker.com/engine/api/v1.41/#operation/ContainerCreate) indicate that `NetworkMode` can be set to `container:<name|id>`. That means that if we know the name of the container, we can use that instead!

Due to the `docker-compose.yml` file, the `orborus` container's name should always be `shuffle-orborus`:
https://github.com/frikky/Shuffle/blob/d77ae8260fd32691d8942dece1957915ba1ff3d5/docker-compose.yml#L41-L45

There is actually already a fallback in the code to default to that, but it doesn't work because `fCol` can't be set to `"0"` at any point in the preceding code.
https://github.com/frikky/Shuffle/blob/d77ae8260fd32691d8942dece1957915ba1ff3d5/functions/onprem/orborus/orborus.go#L112-L115

Regarding, the worker containers, their name is `worker-{Execution ID}`, so `worker.go` could simply use something like
```go
hostConfig.NetworkMode = container.NetworkMode(fmt.Sprintf("container:worker-%s", workflowExecution.ExecutionId))
```
---
I have started to work on a PR, but I've had some trouble building and running the images locally. I'll reach out on Discord to see if I can get it to work.

### PR DESCRIPTION
**Pull request by gc-advens**
Hi!
This is my attempt at fixing #496. This is just a first version to get the conversation started.

I'm fairly confident that this solution is robust for `worker.go`.
Regarding `orborus.go`, I'm unsure about how Kubernetes works, so I've added a `CONTAINER_NAME` environment variable that should allow to specify the container name to use in case it's not `shuffle-orborus`.

I have taken the liberty to remove the `RUNNING_MODE` env variable (Docker / Kubernetes) as I believe it's no longer necessary with this change.

### CODE REVIEW

**Comment by frikky** [comment]
Thanks @gc-advens - fixing this will definitely become a necessity, as I'm assuming most will be moving towards cgroup v2 at some point. I do however not think that it's a good fix, as it requires hard-coded values, which we try to stay away from as much as possible. I recognize that you did attempt to find a way to find the same information through the cgroup v2 value though. What you've added is essentially the way we used to run it, which caused other issues.

Just my suggestion, since I don't have an easy way of testing v2 right now;
Wouldn't it work to keep the getThisContainerId() function, and if the value is still empty (not just shuffle-orborus), we overwrite it with your env (CONTAINER_NAME)? That way we can kind of keep support for both. 

**Check and set in this order:**
1. Check cgroup v1
2. Set based on CONTAINER_NAME if it's defined
3. Set it static to "shuffle-orborus"

It's basically reversing what was done in #110 (@harduino), which probably breaks more than it helps.

**PS:** There may be another way to approach it by figuring out another way to attach to a container network without needing the container name. That's the core reason for this code in the first place.

**Comment by frikky** [comment]
Happy to get on a call to debug this btw. Also; we could build a separate version to use when running cgroup v2 with code similar to this, as not to break the "normal" version of Shuffle.

**Comment by gc-advens** [comment]
Hi @frikky!
I have tried to implement the logic you suggested. Is this what you had in mind?

I haven't reversed the changes to `worker.go`, as the worker containers' names are managed by `orborus.go`, so there's no uncertainty there:
https://github.com/frikky/Shuffle/blob/d77ae8260fd32691d8942dece1957915ba1ff3d5/functions/onprem/orborus/orborus.go#L556

---
> It's basically reversing what was done in #110 (@harduino), which probably breaks more than it helps.

I have taken a look at that PR, and I don't think we're completely reverting the changes. If I understand correctly, [before the PR](https://github.com/frikky/Shuffle/blob/0fc9c783851d0377be6aba0f67cec7be6a119284/functions/onprem/orborus/orborus.go) networking was configured using the NetworkID, which was found by enumerating the containers via the Docker API.

**Comment by frikky** [comment]
Verified that it works - hence can merge in! I (changed and) added the environment variable to .env as well (ORBORUS_CONTAINER_NAME). 

I do know that this may cause problems later on with cgroup v2 because of manual configurations, but I guess we can live with that for now if it fixes your issue :+1:

**Comment by gc-advens** [comment]
Thanks a lot! We updated our server to 0.9.14 and it now works!

**Pull request merged**
