### PR TITLE
App icon changes and new package for app icon crop

### PR DESCRIPTION
**Pull request by amitkinfopercept**
App icon with all feature.

image

image

### CODE REVIEW

**Comment by frikky** [comment]
Oh baby, you really took it to a new level huh. 

This is amazing. I'll try it out and merge it in :dancers:

**Comment by frikky** [comment]
Hey!

I made some fixes over in this branch: https://github.com/frikky/Shuffle/tree/amitkinfopercept-master
In general, this was super useful, but please ALWAYS keep clicks to a minimal. E.g. having to click three times to upload an image is really awful. I got it down to two in the above by making upload happen on the first click as well.

Some more things to look at;
- Why does the "upload image" take a long time/not happen at all sometimes?
- Could we add some kind of "upload image" icon here to the box?
image

Anyways, this is cool and well done, and should really help us out longterm.

**Comment by amitkinfopercept** [comment]
Why does the "upload image" take a long time/not happen at all sometimes? >> it works all the time i have verified, we can cross check if needed
Could we make the API towards the launch branch ;) >> it is against launch branch
Could we add some kind of "upload image" icon here to the box? >> i have added it

image

**Comment by amitkinfopercept** [comment]
@frikky did you get chance to merge the PR.

**Comment by frikky** [comment]
> @frikky did you get chance to merge the PR.

Gonna do it tonight! Have one more task to finish up first

**Comment by frikky** [comment]
It's dooone! I recentered the upload icon and re-fixed the insta-upload button.

Thanks :partying_face:

**Pull request merged**
