### PR TITLE
dynamic environment [feature]

### PR DESCRIPTION
**Pull request by harduino**
The main goal of this feature is to not enter some required data everytime. For example, you can store API-key for Cortex once and then it will be taken automatically for every node.
image
image

### CODE REVIEW

**Comment by frikky** [comment]
This is something I've been planning, but as authentication rather than environments (#26). Environments have a different use that I have to explain properly. Great addition!

Id love to have a chat about what you've done and am planning on doing if you have time later today / tomorrow (mail me if you want: frikky@shuffler.io).

**Comment by harduino** [comment]
@frikky 
Sure, sent you email.

**Comment by frikky** [comment]
Some notes for things to chat about this pull request as this feature is super valuable:
* Should environments (AKA. locations) contain authentication?
* Should an API-key be passed to Orborus/Worker? 
* Should Orborus/Worker/App_sdk be able to get all environments from the backend? (Slows down execution per app, increases load on backend and apps, and reduces security as you get _everything_ and not just what you need)

The approach I've been pondering while making other features:
1. First time you use an app, you set up authentication (which can be multiple) - have these encrypted somehow.
2. If authentication exists for the app, fields tagged as "configuration" or something similar will not appear
3. Have a dropdown (or something similar) that gives you authentication choice for the app - If only one, hide it
4. Have authentication be controlled in the admin panel (as you've done) - don't show the actual credentials, but only re-authenticate
5. Get the authentication in the backend as part of the execution WHEN the workflow executes. Decrypt the value (general Shuffle encryption key), and re-encrypt it with the "Authorization" key, which is unique per execution. 
6. The item is decrypted when it hits the app_sdk with the passed authorization key

**Comment by frikky** [comment]
Hey, thanks for the meeting about this one :hand: 

I've tested it some this morning, and I still like the point of this implementation, but I don't think it's the right one long-term. The thing I didn't understand yesterday (but thought I did), was how exactly the apps themselves could use the variables passed to the apps, which I understood immediately when testing (which I'll do before future meetings ;)) 

The main issue is in the app creation process and mapping that to the environments in the backend. If this was a truly "dynamic environment" feature, the credentials shouldn't need to be filled by the user at all. I think this would be really hard for "normal" users to understand, rather than have a popup asking for credentials. The encryption isn't as vital as it might have seemed from our conversation yesterday, but it's definitely a feature we'd want in the future.

What I'll do now will be to close the issue, but make a much higher priority for the "app authentication" part of Shuffle. Give me a week or two.

**Comment by harduino** [comment]
Hey @frikky 
Thank you for testing and investigating!

I don't see problem if generate/retrieve API-key once and then use it all the time. You can generate manually or automatically API-keys for TheHive, Cortex, MISP and save them in Shuffle's "Dynamic Environment" once and forget about authentication at all. That's purpose of the API-keys for which they were designed. If use credentials every time when node starts - it will make much more work, i.e. send credentials, create/store/pass/delete sessions etc.

Anyway, authentication feature looks promising and should unify authentication stuff.

**Comment by frikky** [comment]
@harduino - Here's an initial commit that handles a lot of the authentication things. The approach ended up being a bit like yours, but doesn't require extra API calls from the backend within every app. Right now, it's not as secure as I'd like it to be (only obscured on frontend), but it's made with ID's to make referencing possible, meaning a user in theory should never be able to see the data when it's properly implemented. 

Here's the commit (#26): https://github.com/frikky/Shuffle/commit/ada6dd9e8dbc3fe9f58fd2a3c3119c97107e0c9f

**Comment by harduino** [comment]
Hey @frikky 
Thanks for that! I'll check when will be able to.

**Pull request closed without merging**
