### PR TITLE
new app sdks

### PR DESCRIPTION
**Pull request by peter-clemenko**
Add jupyter app sdks

### CODE REVIEW

**Comment by peter-clemenko** [comment]
added home assistant for iot stuff

**Comment by frikky** [comment]
I think we need a new strategy for this; we should keep the Dockerfiles you've added, but the app base should be the same everywhere. The only way this can be done well is probably to run a CI pipeline whenever the SDK is updated, which rebuilds all the different SDK's

**Comment by peter-clemenko** [comment]
I believe we've talked about this in the past, and I agree. I suggest installing it as a pip package

**Comment by frikky** [comment]
> I believe we've talked about this in the past, and I agree. I suggest installing it as a pip package

I'll still need to get back to this thought. My brain says there must be consequences for it, but I can't actually think what they would be. I'll leave this open for 1.0.1, as it's not really a pressing issue yet.

**Comment by peter-clemenko** [comment]
Can we merge these PRs in for the mean time?

**Comment by peter-clemenko** [comment]
Closing this for now. The dockerfiles are botched and need to be fixed.

**Pull request closed without merging**
