### PR TITLE
Autodetect Network Feature

### PR DESCRIPTION
**Pull request by harduino**
Before we had hard-coded network "shuffle_shuffle". Here's solution how to automate this. I tried to implement it without using curl & bash (i.e. with using Go Docker lib), but it worked unstable. Method below CURLs to Docker socket & interacts with it to determine container's network name. So all services, including worker & apps will use the same network as parent's

### CODE REVIEW

**Comment by frikky** [comment]
Hey and thanks for contributing :tada: ! I'll look a bit deeper at all your pull requests later today or tomorrow.

To the pull itself: this is a great feature which fixes some issues I had with Windows builds specifically, but I have some issues with it:
1. There is no need to use Curl through a shell subprocess when we have access to the Docker api anyway.
2. I'm trying to keep everything as small as possible. I know it's not really necessary, but this is why I've stuck with Scratch.

I'll probably re-code what you did in pure Go - thanks for taking the effort to get it to work :)

**Comment by harduino** [comment]
Hey @frikky 
I tried to get it work without using bash CURL, i.e. in pure Go, but it had unexpected behavior then, maybe I did something wrong.
P.S. Tested all that issues on Windows & Linux and all worked fine.
P.P.S. Agree, that Scratch makes images smaller, but it's a headache to maintain and search bugs for such containers, e.g. you can't enter within container or rewrite its entrypoint if something went wrong.

**Comment by frikky** [comment]
Hey,

I built an auto-detect mechanism for this that looks for a shuffle named something with "shuffle" and an "orborus" container rather than the current running hostname. This runs in init(), meaning it's only required once. I'll change this to just be based on orborus instead prolly :)

**Comment by frikky** [comment]
Alright, I updated it again. This time, it looks for a RUNNING version of Orborus, and then takes a network with a specified name identifier (shuffle in this case). 

The network name is then passed to the worker, which makes sure the apps also run under the same network. This seems to fix network issues on Windows too.

**Comment by harduino** [comment]
Hey @frikky 
I'm glad to hear that!

**Pull request closed without merging**
